/**
 * The demo school's social side (Phase 3): course discussions with their replies, comments under
 * lessons, reports for the moderation queue, live classes with their chat, and what the scripted
 * classmates say in a live class's chat. seedSocial.js turns it into the API's data; validate.js
 * checks it against the API's rules.
 *
 * Times are days ago (`daysAgo`, fractional), or for live classes minutes from now
 * (`startsInMinutes`), so the demo always looks recent. People and courses are content.js's keys.
 * Questions are about each course's actual lessons, and the instructors' answers are accurate.
 */

// Course discussions --------------------------------------------------------------------------------
// A thread: key (unique in its course), author, daysAgo, title, body; optionally pinned, locked,
// deleted (by its author, leaving a placeholder for its replies), hidden: { daysAgo } (by a
// moderator), votes (how many found it helpful), voters (who, by name, among them), replies.
// A reply: key, author, daysAgo, body; optionally accepted, hidden, votes, voters.

export const THREADS = {
  'linear-algebra-visually': [
    {
      key: 'welcome',
      author: 'daniel',
      daysAgo: 45.8,
      pinned: true,
      votes: 24,
      title: 'Welcome! Introduce yourself here',
      body: `Hi everyone, and welcome to Linear Algebra, Visually. I'm Daniel, and I'll be around in these discussions most days.

Tell us who you are, where you're joining from, and what brought you here: graphics, machine learning, physics, an exam, or plain curiosity are all good reasons.

A few tips:
- Watch each lecture once straight through, then again with the notes open.
- Ask questions here, so everyone benefits from the answers. A question about one lesson can also go in the comments under it.
- Mark the replies that helped you as helpful, so they're easy to find later.`,
      replies: [
        {
          key: 'kwame',
          author: 'kwame',
          daysAgo: 44.9,
          votes: 3,
          body: 'Kwame, from Accra. Second-year engineering student: our lecturer shows us the rules for multiplying matrices but never why they work, so I’m hoping this fills in the why.',
        },
        {
          key: 'maya',
          author: 'maya',
          daysAgo: 44.2,
          votes: 4,
          body: 'Hi, I’m Maya. I studied this at university twenty years ago and remember nothing except “ad minus bc”. Looking forward to finally knowing what it means.',
        },
        {
          key: 'lucia',
          author: 'lucia',
          daysAgo: 41.5,
          votes: 2,
          body: 'Lucía, from Seville. I make small games as a hobby and keep running into rotation matrices, so it’s time I understood them properly.',
        },
        {
          key: 'hana',
          author: 'hana',
          daysAgo: 37.5,
          votes: 3,
          body: 'Hello from Osaka! I work as a data analyst and use matrices in Python every day without really picturing them. I’m here for the pictures.',
        },
        {
          key: 'daniel-hana',
          author: 'daniel',
          daysAgo: 37.4,
          votes: 5,
          body: 'Welcome, all of you. Maya, by the end of the determinant lesson, ad − bc will be something you can see: how much a transformation grows or shrinks areas.',
        },
        {
          key: 'hugo',
          author: 'hugo',
          daysAgo: 20.0,
          hidden: { daysAgo: 19.1 },
          body: 'Want top marks without the work? I write assignments and quiz answers for any course here, fast and cheap. Message me for prices.',
        },
        {
          key: 'sara',
          author: 'sara',
          daysAgo: 20.3,
          votes: 2,
          body: 'Sara, Stockholm. Machine learning is the goal; linear algebra is the step I keep skipping. Not this time.',
        },
        {
          key: 'priya',
          author: 'priya',
          daysAgo: 19.2,
          votes: 2,
          body: 'Priya, from Bangalore. I’m a software developer moving into computer graphics, and every tutorial I read assumes I already think in matrices.',
        },
        {
          key: 'amira',
          author: 'amira',
          daysAgo: 13.5,
          votes: 4,
          body: 'Hi everyone, I’m Amira, joining from Amman. I’m studying computer science part-time and want to understand the maths behind graphics. The animations are already helping a lot.',
        },
        {
          key: 'zara',
          author: 'zara',
          daysAgo: 6.5,
          votes: 2,
          body: 'Hey all, Zara here. Same reason as Amira and Priya: I want to write shaders and actually understand what they’re doing to every pixel.',
        },
        {
          key: 'arjun',
          author: 'arjun',
          daysAgo: 2.8,
          votes: 1,
          body: 'Arjun, from Pune. Just finished the neural networks course here and realised half of it was linear algebra, so here I am.',
        },
      ],
    },
    {
      key: 'columns',
      author: 'priya',
      daysAgo: 18.5,
      votes: 9,
      title: 'Why does a matrix only need to know where î and ĵ land?',
      body: 'In the transformations lesson, the whole matrix is just two columns: where î goes and where ĵ goes. But the transformation moves every vector in the plane. How can two vectors be enough to pin down where all the others go?',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 18.3,
          accepted: true,
          votes: 12,
          voters: ['amira'],
          body: `Because every vector is a combination of î and ĵ. The vector (3, −2) means 3·î + (−2)·ĵ. A linear transformation keeps that recipe intact: it sends 3·î + (−2)·ĵ to 3·(where î lands) + (−2)·(where ĵ lands).

That's exactly what "grid lines stay parallel and evenly spaced" guarantees. So once you know the two landing spots, every other vector is decided. It's also why the trick only works for linear transformations: bend the grid, and the recipe breaks.`,
        },
        {
          key: 'priya',
          author: 'priya',
          daysAgo: 18.1,
          votes: 2,
          body: 'That’s the bit I was missing: the recipe (3, −2) stays the same, only the ingredients move. Thank you!',
        },
        {
          key: 'mateo',
          author: 'mateo',
          daysAgo: 10.9,
          votes: 3,
          body: 'Same idea in 3D, by the way: three columns, for where î, ĵ and k̂ land.',
        },
      ],
    },
    {
      key: 'order',
      author: 'amira',
      daysAgo: 3.2,
      votes: 6,
      title: 'BA means “A first, then B”? I keep getting the order backwards',
      body: 'In the composition lesson, applying A and then B is written BA. My brain wants to read left to right, so I keep writing AB. Is there a way to remember this, or a reason it’s written that way round?',
      replies: [
        {
          key: 'kwame',
          author: 'kwame',
          daysAgo: 3.0,
          votes: 4,
          voters: ['amira'],
          body: 'Think of it like functions: f(g(x)) means g first, then f. A matrix acts on the vector to its right, so in BAv, A touches v first.',
        },
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 2.8,
          accepted: true,
          votes: 9,
          voters: ['amira'],
          body: `Kwame's right, and it's worth saying why it's written that way. The vector sits on the right, and each matrix acts on whatever is to its right. So in BAv, A meets v first, then B acts on the result.

A check that always works: take the 90° rotation R and the shear S with columns (1, 0) and (1, 1), apply both orders to î by hand, and compare. RS and SR send î to different places, so only one order can be right.`,
        },
        {
          key: 'amira',
          author: 'amira',
          daysAgo: 2.6,
          votes: 1,
          body: 'Doing it by hand with î made it stick: RS and SR really do send î to different places. Thanks, both of you!',
        },
        {
          key: 'felix',
          author: 'felix',
          daysAgo: 0.4,
          votes: 1,
          body: 'Saving this thread. I had exactly the same problem on the quiz.',
        },
      ],
    },
    {
      key: 'rotation',
      author: 'lucas',
      daysAgo: 6.0,
      votes: 7,
      title: 'Is the determinant of every rotation exactly 1?',
      body: 'The “Try it” in the determinant lesson asks about the 90° rotation. I got 0·0 − (−1)·1 = 1. Does every rotation have determinant 1, whatever the angle?',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 5.8,
          accepted: true,
          votes: 8,
          body: 'Yes. A rotation by θ has columns (cos θ, sin θ) and (−sin θ, cos θ), so its determinant is cos²θ + sin²θ = 1. That matches the picture: turning the plane doesn’t change any areas, and it doesn’t flip anything over.',
        },
        {
          key: 'lucas',
          author: 'lucas',
          daysAgo: 5.7,
          votes: 2,
          body: 'And a reflection would be −1, then? Same area, but flipped over.',
        },
        {
          key: 'daniel-2',
          author: 'daniel',
          daysAgo: 5.6,
          votes: 4,
          body: 'Exactly. Reflections have determinant −1: areas unchanged, orientation reversed.',
        },
      ],
    },
    {
      key: 'span-check',
      author: 'hana',
      daysAgo: 26.0,
      votes: 5,
      title: 'Do (1, 2) and (2, 4) span the plane?',
      body: 'The span lesson asks this in “Check yourself”. I think the answer is no, because (2, 4) is just (1, 2) doubled. But then what do they span?',
      replies: [
        {
          key: 'grace',
          author: 'grace',
          daysAgo: 25.8,
          accepted: true,
          votes: 6,
          body: 'You’re right: they’re linearly dependent, so together they only reach the line through the origin in the direction of (1, 2). Every combination a·(1, 2) + b·(2, 4) is (a + 2b)·(1, 2). (1, 2) and (2, 1), on the other hand, point in different directions, so they span the whole plane.',
        },
        {
          key: 'hana',
          author: 'hana',
          daysAgo: 25.6,
          votes: 1,
          body: '(a + 2b)·(1, 2) is a neat way to see it. Thanks, Grace!',
        },
      ],
    },
    {
      key: 'quiz-answers',
      author: 'felix',
      daysAgo: 9.5,
      locked: true,
      title: 'Answers to “Check your understanding”?',
      body: 'Has anyone got all five right? I’m on my last attempt and would like to compare answers before I try again.',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 9.3,
          votes: 6,
          body: 'I’m going to lock this one. Please don’t post quiz answers: the quiz is there so you can check your own understanding, and the explanations appear once you pass or run out of attempts. If a question is confusing, start a thread about the idea behind it and I’ll gladly help.',
        },
      ],
    },
    {
      key: 'project-3d',
      author: 'mateo',
      daysAgo: 10.0,
      deleted: true,
      title: 'Can the project use a 3×3 matrix?',
      body: 'I’d like to do the project in 3D instead. Is a 3×3 matrix allowed?',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 9.8,
          votes: 3,
          body: 'Please stick to 2×2 for the main answer, so the before-and-after drawing stays manageable. If you enjoy it, add a 3×3 example at the end as a bonus; I’ll read it with interest.',
        },
        {
          key: 'ivan',
          author: 'ivan',
          daysAgo: 9.5,
          votes: 1,
          body: 'Thanks, that answers my question too.',
        },
      ],
    },
    {
      key: 'determinant-3d',
      author: 'sara',
      daysAgo: 1.6,
      votes: 3,
      title: 'How do I picture a 3×3 determinant?',
      body: 'In 2D the determinant scales area. Is it volume in 3D? I tried to picture a cube being sheared and squashed but got lost. Any tips for visualising it?',
      replies: [],
    },
    {
      key: 'study-group',
      author: 'noah',
      daysAgo: 4.0,
      votes: 4,
      title: 'Anyone want to form a study group for the project?',
      body: 'I learn better by talking things through. Would anyone like to meet online once this week to compare ideas for the transformation project? No sharing finished answers, just ideas.',
      replies: [
        {
          key: 'zara',
          author: 'zara',
          daysAgo: 3.8,
          votes: 1,
          body: 'Count me in. Weekday evenings (UTC) work best for me.',
        },
        {
          key: 'adam',
          author: 'adam',
          daysAgo: 3.5,
          body: 'Selling my old linear algebra textbook, barely used, half price. Message me if you’re interested!',
        },
        {
          key: 'amira',
          author: 'amira',
          daysAgo: 3.1,
          votes: 1,
          body: 'I’d join too, if it’s after 18:00 UTC. I’m planning a shear followed by a stretch, so it would be good to hear other ideas.',
        },
      ],
    },
  ],

  'calculus-first-steps': [
    {
      key: 'welcome',
      author: 'daniel',
      daysAgo: 21.0,
      pinned: true,
      votes: 11,
      title: 'Welcome to Calculus: First Steps',
      body: `Hello and welcome! This is a short course, so it's a good one to finish.

Say hello below and tell us what you'd like calculus for. If anything in a lecture goes too fast, ask here: there are no silly questions in calculus, only steps someone skipped.`,
      replies: [
        { key: 'arjun', author: 'arjun', daysAgo: 20.8, votes: 2, body: 'Hi! Arjun here. I want the calculus behind gradient descent, so this seemed the right place to start.' },
        { key: 'hana', author: 'hana', daysAgo: 20.5, votes: 1, body: 'Hana, from Osaka. Revisiting calculus after many years; the circle-into-rings animation already made it worth it.' },
        { key: 'maya', author: 'maya', daysAgo: 20.2, votes: 1, body: 'Maya here, helping my son with his physics homework and realising I need this first.' },
        { key: 'samuel', author: 'samuel', daysAgo: 12.5, votes: 1, body: 'Samuel. Physics is my goal, and every physics book I open starts with derivatives.' },
      ],
    },
    {
      key: 't-cubed',
      author: 'ivan',
      daysAgo: 9.0,
      votes: 6,
      title: 'Where does the 3 in 3t² come from?',
      body: 'In the paradox of the derivative, the derivative of t³ comes out as 3t². I followed the animation, but not where the 3 comes from. Can someone spell it out?',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 8.8,
          accepted: true,
          votes: 10,
          body: `Expand (t + dt)³ = t³ + 3t²·dt + 3t·dt² + dt³. Subtract t³ to get the change: 3t²·dt + 3t·dt² + dt³. Divide by dt: 3t² + 3t·dt + dt². As dt shrinks towards zero, the last two terms vanish and 3t² is left.

The 3 counts the three ways one of the three factors of (t + dt) can contribute its dt: in the cube picture, those are the three thin slabs on its faces.`,
        },
        { key: 'ivan', author: 'ivan', daysAgo: 8.6, votes: 2, body: 'The three slabs! That’s what the cube animation was showing. Thank you.' },
      ],
    },
    {
      key: 'gravity',
      author: 'nadia',
      daysAgo: 2.0,
      votes: 3,
      title: 'Falling phone: g = 9.8 or 10?',
      body: 'For the falling phone problem, should we use g = 9.8 m/s², or is 10 fine? My answers come out slightly different.',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 1.8,
          accepted: true,
          votes: 4,
          body: 'Use 9.8 m/s², and say so in your answer. With 10 you’d be off by about 2%, which isn’t wrong as an estimate, but stating your assumptions is part of the exercise.',
        },
      ],
    },
    {
      key: 'circle',
      author: 'maya',
      daysAgo: 15.0,
      votes: 5,
      title: 'Why is the triangle’s height 2πR?',
      body: 'In the essence of calculus, the rings line up into a triangle. I see that its base is R, but why is its height 2πR?',
      replies: [
        {
          key: 'arjun',
          author: 'arjun',
          daysAgo: 14.7,
          accepted: true,
          votes: 5,
          body: 'Each ring, unrolled, is about as long as its circumference, 2πr. The outermost ring has r = R, so the tallest rectangle, at the right-hand edge, is 2πR tall. Half the base times the height: ½ · R · 2πR = πR².',
        },
        { key: 'maya', author: 'maya', daysAgo: 14.5, votes: 1, body: 'Of course: the last ring is the circumference of the whole circle. Thank you!' },
      ],
    },
  ],

  'physics-of-sound': [
    {
      key: 'welcome',
      author: 'daniel',
      daysAgo: 18.2,
      pinned: true,
      votes: 14,
      title: 'Welcome to The Physics of Sound',
      body: `Welcome! These are Grand Academy's own videos, made for this course: every tone you hear was synthesised from the same maths the lessons describe.

Headphones help, especially for the low tones and the beats. Say hello below, and if you play an instrument, tell us which: it'll come in handy when we get to timbre.`,
      replies: [
        { key: 'hugo', author: 'hugo', daysAgo: 18.0, votes: 2, body: 'Hugo, guitar player. I tune by ear using beats without ever knowing why it worked. Here to find out.' },
        { key: 'zara', author: 'zara', daysAgo: 16.8, votes: 3, body: 'Hi! Violin, badly. Looking forward to timbre.' },
        { key: 'chloe', author: 'chloe', daysAgo: 16.5, votes: 1, body: 'Chloé, from Lyon. I sing in a choir and want to understand why some chords sound “rough”.' },
        {
          key: 'amira',
          author: 'amira',
          daysAgo: 5.5,
          votes: 2,
          body: 'Hello! No instrument, but I mix music as a hobby and want to understand what the equaliser is actually doing.',
        },
        {
          key: 'daniel-amira',
          author: 'daniel',
          daysAgo: 5.4,
          votes: 2,
          body: 'Welcome, Amira! Then you’ll enjoy the timbre lesson: an equaliser turns the harmonics of a sound up and down.',
        },
      ],
    },
    {
      key: 'decibels',
      author: 'amira',
      daysAgo: 2.1,
      votes: 5,
      title: 'Why does ten times the energy only sound twice as loud?',
      body: 'The loudness notes say every 10 dB is ten times the sound energy, which we hear as roughly twice as loud. Why isn’t ten times the energy ten times as loud? Is it our ears, or the decibel scale?',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 1.9,
          accepted: true,
          votes: 7,
          voters: ['amira'],
          body: `It's our ears, and the decibel scale was designed around them. Our sense of loudness is roughly logarithmic: to sound twice as loud, a sound needs about ten times the energy. That's what lets us hear a whisper and a jet engine with the same pair of ears, across a range of about a trillion to one in energy.

Decibels just count those multiplications: +10 dB is ×10 energy, +20 dB is ×100, +30 dB is ×1000. So going from 60 dB to 80 dB is a hundred times the energy, but only about four times as loud.`,
        },
        {
          key: 'noah',
          author: 'noah',
          daysAgo: 1.2,
          votes: 2,
          body: 'This also explains why a phone’s volume steps feel even: they’re steps in decibels, not in energy.',
        },
      ],
    },
    {
      key: 'hearing-range',
      author: 'zara',
      daysAgo: 14.0,
      votes: 6,
      title: 'Can people really hear up to 20,000 Hz?',
      body: 'I tried a hearing test online and couldn’t hear anything above about 16,000 Hz. Is something wrong with my ears?',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 13.8,
          accepted: true,
          votes: 8,
          body: 'Almost certainly not. 20 Hz to 20,000 Hz is the range for young ears; the top end drops steadily with age, and most adults can’t hear much above 15,000 to 17,000 Hz. Small speakers and cheap headphones often can’t play those frequencies either, so the test may not have been producing them at all.',
        },
        { key: 'zara', author: 'zara', daysAgo: 13.6, votes: 1, body: 'Phew. And my laptop speakers are definitely cheap.' },
      ],
    },
    {
      key: 'beat-apps',
      author: 'sienna',
      daysAgo: 4.0,
      votes: 3,
      title: 'Beat lab: which apps can play two tones at once?',
      body: 'For the lab I need two tones playing together. Any free tone generators that do this? My phone app only plays one at a time.',
      replies: [
        {
          key: 'kwame',
          author: 'kwame',
          daysAgo: 3.8,
          votes: 5,
          body: 'Two phones side by side work well: one on 440 Hz, one on 442 Hz. Or look for a browser tone generator that lets you add a second oscillator; most free ones can.',
        },
        {
          key: 'oliver',
          author: 'oliver',
          daysAgo: 3.0,
          body: 'Honestly this whole course is too easy. If you need help finding an app, maybe physics isn’t for you.',
        },
        { key: 'sienna', author: 'sienna', daysAgo: 2.9, votes: 1, body: 'Two phones it is. Thanks, Kwame!' },
      ],
    },
    {
      key: 'odd-harmonics',
      author: 'hugo',
      daysAgo: 1.0,
      votes: 4,
      title: 'Why does a clarinet only have odd harmonics?',
      body: 'The timbre lesson says odd harmonics only sound hollow, a bit like a clarinet. Why would an instrument produce only the odd ones?',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 0.8,
          accepted: true,
          votes: 4,
          body: `Mostly because of its shape. A clarinet behaves like a tube closed at one end (the reed) and open at the other. Such a tube can only hold standing waves where the pressure swings most at the closed end and not at all at the open end, and those fit only odd numbers of quarter-wavelengths. That gives the odd harmonics: 1, 3, 5... A flute is open at both ends and has all of them.

We'll draw these standing waves in the resonance lesson, once it's published.`,
        },
      ],
    },
  ],

  'neural-networks': [
    {
      key: 'welcome',
      author: 'sofia',
      daysAgo: 30.0,
      pinned: true,
      votes: 12,
      title: 'Welcome to Neural Networks: The Big Ideas',
      body: `Welcome! I'm Sofia. No programming is needed here: we follow one network that reads handwritten digits, from pixels to the calculus that trains it.

Introduce yourself below, and tell us where you've met neural networks before: a phone's photo search, a translation app, a chatbot...`,
      replies: [
        { key: 'lucia', author: 'lucia', daysAgo: 29.8, votes: 1, body: 'Lucía. My phone sorts my photos by face and I’d like to know how.' },
        { key: 'nadia', author: 'nadia', daysAgo: 29.0, votes: 2, body: 'Nadia, from Dhaka. I work in a hospital lab where we’re starting to use image classifiers, and I want to understand what they do.' },
        { key: 'arjun', author: 'arjun', daysAgo: 27.5, votes: 1, body: 'Arjun. Mostly curiosity, and a little fear of missing out.' },
      ],
    },
    {
      key: 'squashing',
      author: 'arjun',
      daysAgo: 22.0,
      votes: 8,
      title: 'Why squash with a sigmoid at all?',
      body: 'Each neuron takes a weighted sum and then squashes it. What would go wrong if we skipped the squashing and just passed the weighted sum on?',
      replies: [
        {
          key: 'sofia',
          author: 'sofia',
          daysAgo: 21.8,
          accepted: true,
          votes: 9,
          body: 'Without a nonlinear step, every layer is just a matrix multiplication plus a shift. Stack any number of those and you get... one matrix multiplication plus a shift. A hundred layers would be no more powerful than one. The squashing (a sigmoid, or ReLU in most modern networks) is what lets layers build on each other to represent complicated shapes.',
        },
        {
          key: 'elena',
          author: 'elena',
          daysAgo: 13.0,
          votes: 3,
          body: 'This connects nicely with the linear algebra course: composing linear maps always gives another linear map.',
        },
      ],
    },
    {
      key: 'local-minimum',
      author: 'elena',
      daysAgo: 12.0,
      votes: 5,
      title: 'Does it matter that gradient descent only finds a local minimum?',
      body: 'The gradient descent lesson says it finds a local minimum, “which is usually good enough”. Why is it good enough? Couldn’t the network get stuck somewhere bad?',
      replies: [
        {
          key: 'sofia',
          author: 'sofia',
          daysAgo: 11.8,
          accepted: true,
          votes: 6,
          body: 'In theory, yes; in practice, less than you’d fear. Networks with many weights have cost surfaces where most local minima are about as good as each other. Training also uses noisy mini-batch steps, which helps it shake loose from poor spots.',
        },
      ],
    },
    {
      key: 'mini-batches',
      author: 'samuel',
      daysAgo: 3.0,
      votes: 4,
      title: 'Mini-batches: is it still gradient descent if every step uses different data?',
      body: 'The backpropagation lesson splits the training data into mini-batches. If each step only looks at a small batch, isn’t every step going in a slightly wrong direction?',
      replies: [
        {
          key: 'sofia',
          author: 'sofia',
          daysAgo: 2.8,
          accepted: true,
          votes: 5,
          body: 'Each step is slightly wrong, yes. A mini-batch gives a rough estimate of the true gradient, a bit like asking a hundred people for directions instead of everyone. The steps wander, but on average they head downhill, and you can take many more of them for the same work. That’s stochastic gradient descent.',
        },
      ],
    },
  ],

  'how-computers-work': [
    {
      key: 'welcome',
      author: 'sofia',
      daysAgo: 57.9,
      pinned: true,
      votes: 15,
      title: 'Welcome to How Computers Work',
      body: 'Welcome! From the abacus to the transistor in three lectures, then logic gates. Say hello below, and tell us the oldest computer you’ve ever used.',
      replies: [
        { key: 'priya', author: 'priya', daysAgo: 57.0, votes: 2, body: 'Priya. A hand-me-down laptop with 512 MB of memory, which felt enormous at the time.' },
        { key: 'nadia', author: 'nadia', daysAgo: 56.5, votes: 3, body: 'Nadia: my grandfather’s slide rule. Does that count?' },
        { key: 'haruto', author: 'haruto', daysAgo: 56.0, votes: 1, body: 'Haruto. A pocket calculator with a solar panel. I still have it, and it still works.' },
      ],
    },
    {
      key: 'xor',
      author: 'amira',
      daysAgo: 7.5,
      votes: 5,
      title: 'Can XOR be built from AND, OR and NOT?',
      body: 'The logic gates lesson lists XOR next to the others. Is it its own kind of gate, or can it be made from AND, OR and NOT?',
      replies: [
        {
          key: 'sofia',
          author: 'sofia',
          daysAgo: 7.3,
          accepted: true,
          votes: 6,
          voters: ['amira'],
          body: `It can be made from them: A XOR B = (A OR B) AND NOT (A AND B). In words: at least one is true, but not both. Check it against the truth table in the notes; it matches row by row.

In fact every gate can be built from NAND gates alone, which is one reason chips are often made that way.`,
        },
        { key: 'amira', author: 'amira', daysAgo: 7.1, votes: 1, body: 'Checked all four rows: it matches. NAND being enough for everything is wild.' },
        { key: 'adam', author: 'adam', daysAgo: 6.0, votes: 2, body: 'Fun follow-up: try building NOT from a single NAND gate. It’s one wire away.' },
      ],
    },
    {
      key: 'bug',
      author: 'tomas',
      daysAgo: 15.0,
      votes: 7,
      title: 'Is a moth really where “bug” comes from?',
      body: 'The electronic computing lecture mentions an insect in a relay. Is that really where the word “bug” comes from?',
      replies: [
        {
          key: 'sofia',
          author: 'sofia',
          daysAgo: 14.8,
          accepted: true,
          votes: 8,
          body: 'Not quite. In 1947, operators of the Harvard Mark II found a moth stuck in one of its relays and taped it into the logbook as the “first actual case of bug being found”. The joke works because engineers were already calling glitches bugs: Thomas Edison used the word in the 1870s.',
        },
      ],
    },
    {
      key: 'transistors',
      author: 'bilal',
      daysAgo: 28.0,
      votes: 4,
      title: 'How many transistors are in a phone chip?',
      body: 'The lecture says modern chips hold billions of transistors. How many, roughly, in the phone in my pocket?',
      replies: [
        {
          key: 'sofia',
          author: 'sofia',
          daysAgo: 27.8,
          accepted: true,
          votes: 5,
          body: 'For a recent phone, well over ten billion, each a switch only a few nanometres across. The first commercial microprocessor, Intel’s 4004 from 1971, had about 2,300.',
        },
      ],
    },
  ],

  'code-your-first-website': [
    {
      key: 'welcome',
      author: 'sofia',
      daysAgo: 12.1,
      pinned: true,
      votes: 6,
      title: 'Welcome, and share what your page is about',
      body: 'Welcome! By the end of this course you’ll have a page of your own. Tell us below what you’re planning to build it about: a hobby, a place, a person you admire...',
      replies: [
        { key: 'tomas', author: 'tomas', daysAgo: 11.9, votes: 2, body: 'Tomás: a page about the hiking trails near my town, with photos.' },
        { key: 'fatima', author: 'fatima', daysAgo: 11.5, votes: 3, body: 'Fatima Zahra: my grandmother’s recipes, before they’re lost.' },
      ],
    },
    {
      key: 'broken-image',
      author: 'maya',
      daysAgo: 8.0,
      votes: 6,
      title: 'My image shows as a broken icon',
      body: 'I added <img src="photos/cat.jpg" alt="My cat Miso"> but the page only shows a broken image icon and the alt text. The photo is definitely on my computer.',
      replies: [
        {
          key: 'sofia',
          author: 'sofia',
          daysAgo: 7.8,
          accepted: true,
          votes: 7,
          body: 'The path in src is relative to your index.html: src="photos/cat.jpg" means a folder called photos, next to index.html, with cat.jpg inside. Check that the folder really is there, and that the name matches exactly, including capitals and the extension (.jpg and .jpeg are different).',
        },
        { key: 'maya', author: 'maya', daysAgo: 7.7, votes: 2, body: 'It was cat.JPG. Capital letters! Fixed, thank you.' },
      ],
    },
    {
      key: 'closing-p',
      author: 'kofi',
      daysAgo: 5.0,
      votes: 3,
      title: 'Do I need to close <p> tags?',
      body: 'My page looks the same whether or not I write </p>. Do I need it?',
      replies: [
        {
          key: 'emma',
          author: 'emma',
          daysAgo: 4.8,
          accepted: true,
          votes: 4,
          body: 'Browsers will usually guess where a paragraph ends if you leave out </p>, but close them anyway: it’s easier to read, and it saves surprises when you start styling the page.',
        },
      ],
    },
  ],

  'big-ideas': [
    {
      key: 'welcome',
      author: 'lena',
      daysAgo: 63.9,
      pinned: true,
      votes: 10,
      title: 'Welcome! Which lecture surprised you most?',
      body: 'Hello and welcome! I’m Lena, and I run Grand Academy. This course is a taster: four big subjects in four short lectures. Watch them in any order, and tell us below which one surprised you most.',
      replies: [
        { key: 'mateo', author: 'mateo', daysAgo: 63.5, votes: 2, body: 'The nucleus. I never knew there was a force strong enough to hold protons together against their own repulsion.' },
        { key: 'priya', author: 'priya', daysAgo: 61.0, votes: 1, body: 'Astronomy: almost everything we know about space comes from light. That changed how I look at the night sky.' },
        { key: 'felix', author: 'felix', daysAgo: 54.0, votes: 1, body: 'Astronomy for me too. I went outside afterwards and just looked up for a while.' },
      ],
    },
    {
      key: 'isotopes',
      author: 'nadia',
      daysAgo: 30.0,
      votes: 5,
      title: 'Why are some isotopes radioactive?',
      body: 'The nucleus lecture explains isotopes: same protons, different numbers of neutrons. Why are some of them radioactive and others stable?',
      replies: [
        {
          key: 'grace',
          author: 'grace',
          daysAgo: 29.5,
          accepted: true,
          votes: 6,
          body: 'It comes down to the balance of protons and neutrons. The strong force holds the nucleus together while the protons repel each other; with too many or too few neutrons for the number of protons, the nucleus is unstable, and sooner or later it changes into something more stable, giving off radiation as it does.',
        },
      ],
    },
    {
      key: 'opportunity-cost',
      author: 'mei',
      daysAgo: 6.0,
      votes: 4,
      title: 'The opportunity cost of watching these lectures',
      body: 'Half joking: the economics lecture says every choice has an opportunity cost. Mine was an episode of a TV series. Worth it.',
      replies: [{ key: 'lena', author: 'lena', daysAgo: 5.8, votes: 3, body: 'Best trade-off I’ve read all week.' }],
    },
  ],

  'first-civilizations': [
    {
      key: 'welcome',
      author: 'omar',
      daysAgo: 35.2,
      pinned: true,
      votes: 13,
      title: 'Welcome to The First Civilizations',
      body: `Welcome! I'm Omar. We'll travel to three river valleys and ask why the first cities grew where they did.

Introduce yourself below, and tell us one place from the ancient world you'd love to visit.`,
      replies: [
        { key: 'grace', author: 'grace', daysAgo: 35.0, votes: 2, body: 'Grace, from Lagos. Mohenjo-daro, to walk its grid of streets.' },
        { key: 'lina', author: 'lina', daysAgo: 34.8, votes: 2, body: 'Lina, from Beirut. Ur, in Mesopotamia: I grew up hearing about it.' },
        { key: 'amara', author: 'amara', daysAgo: 34.0, votes: 1, body: 'Amara. The pyramids at Giza, obviously, but at dawn before the crowds.' },
        { key: 'kofi', author: 'kofi', daysAgo: 28.5, votes: 1, body: 'Kofi. Babylon, to see where Hammurabi’s laws were written.' },
        { key: 'amira', author: 'amira', daysAgo: 19.5, votes: 2, body: 'Amira, from Amman. Petra is close to home, so for something new: the Nile valley at flood time.' },
        { key: 'omar-amira', author: 'omar', daysAgo: 19.4, votes: 1, body: 'Welcome, Amira! The flood is exactly where the Egypt lecture begins.' },
      ],
    },
    {
      key: 'indus-script',
      author: 'ines',
      daysAgo: 14.0,
      votes: 7,
      title: 'Why can’t anyone read the Indus script?',
      body: 'The Indus Valley lesson says their script still hasn’t been deciphered. We can read Egyptian hieroglyphs and cuneiform, so what makes this one so hard?',
      replies: [
        {
          key: 'omar',
          author: 'omar',
          daysAgo: 13.8,
          accepted: true,
          votes: 8,
          body: 'Three things work against us. The inscriptions are very short, usually about five symbols on a seal, which gives too little to work with. We don’t know which language they wrote. And there’s no bilingual text, nothing like the Rosetta Stone, which let scholars match Egyptian hieroglyphs to Greek. Without one of those footholds, many decipherments have been proposed and none is accepted.',
        },
      ],
    },
    {
      key: 'hammurabi',
      author: 'kofi',
      daysAgo: 15.0,
      votes: 6,
      title: 'Did Hammurabi’s laws apply equally to everyone?',
      body: '“An eye for an eye” sounds harsh but at least equal. Did the code treat everyone the same?',
      replies: [
        {
          key: 'omar',
          author: 'omar',
          daysAgo: 14.8,
          accepted: true,
          votes: 7,
          body: 'No, and that’s one of the most revealing things about it. Penalties depended on who you were: harming a free man brought a harsher punishment than harming a commoner or an enslaved person, and “an eye for an eye” applied between equals. The code shows a society that took law seriously and took social rank for granted.',
        },
      ],
    },
    {
      key: 'salinisation',
      author: 'amira',
      daysAgo: 0.9,
      votes: 2,
      title: 'How fast did salt actually ruin Mesopotamian fields?',
      body: 'My essay feedback asked me to say more about salinisation. Was it a slow change over centuries, or could a field be ruined in a few years?',
      replies: [
        {
          key: 'omar',
          author: 'omar',
          daysAgo: 0.6,
          votes: 2,
          body: 'Mostly slow, over centuries. Irrigation water carries a little dissolved salt; when it evaporates in the fields, the salt stays behind, year after year. Records from southern Mesopotamia suggest farmers shifted from wheat to the more salt-tolerant barley over many generations as yields fell. A badly drained field could decline within a few decades, but the big shift took a very long time.',
        },
      ],
    },
  ],
};

// Lesson comments ----------------------------------------------------------------------------------
// A comment: key (unique in its course), lesson, author, daysAgo, body; optionally votes, voters, replies.

export const COMMENTS = {
  'linear-algebra-visually': [
    {
      key: 'three-views',
      lesson: 'vectors',
      author: 'sienna',
      daysAgo: 10.0,
      votes: 7,
      body: 'The three views (an arrow, a list of numbers, anything you can add and scale) finally made this click. I’d only ever seen the list-of-numbers version.',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 9.8,
          votes: 3,
          body: 'Glad it helped. Keep all three in mind: the arrow view is the one we’ll lean on most in this course.',
        },
      ],
    },
    {
      key: 'tip-to-tail',
      lesson: 'vectors',
      author: 'amira',
      daysAgo: 13.0,
      votes: 3,
      body: 'Tip for anyone else new: sketching (2, 1) + (−1, 3) tip to tail on squared paper and landing on (1, 4) made the adding rule feel obvious.',
      replies: [
        {
          key: 'noah',
          author: 'noah',
          daysAgo: 11.0,
          votes: 1,
          body: 'Nice. I did the same, then tried (2, 1) − (−1, 3): subtracting is just adding the flipped arrow.',
        },
      ],
    },
    {
      key: 'origin',
      lesson: 'transformations',
      author: 'ethan',
      daysAgo: 28.0,
      votes: 8,
      body: 'Why does the origin have to stay put? A shift (moving everything one step right) keeps grid lines parallel and evenly spaced too.',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 27.8,
          accepted: true,
          votes: 9,
          body: 'Good catch: a shift keeps the lines parallel, but it isn’t linear, because it moves the origin. A linear map has to send the zero vector to zero (scale any vector by 0 before or after, and you must get the same answer). Shifts are “affine” transformations; graphics programs handle them with a trick that uses one extra coordinate.',
        },
      ],
    },
    {
      key: 'shear',
      lesson: 'determinant',
      author: 'kwame',
      daysAgo: 5.0,
      votes: 5,
      body: 'Worth pausing to check the shear with columns (1, 0) and (1, 1): det = 1·1 − 1·0 = 1. The square leans over but keeps its area, exactly like the animation.',
      replies: [],
    },
  ],
  'calculus-first-steps': [
    {
      key: 'approximation',
      lesson: 'derivative-paradox',
      author: 'samuel',
      daysAgo: 7.0,
      votes: 4,
      body: 'Thinking of the derivative not as “change at an instant” but as the best constant rate near a point was a revelation. Thank you for this one.',
      replies: [],
    },
  ],
  'physics-of-sound': [
    {
      key: 'headphones',
      lesson: 'what-is-sound',
      author: 'aisha',
      daysAgo: 10.0,
      votes: 6,
      body: 'Headphones make a big difference for the 220 Hz tone. On my laptop speakers I could barely hear it.',
      replies: [
        { key: 'daniel', author: 'daniel', daysAgo: 9.8, votes: 2, body: 'Good tip. Small speakers struggle with low notes, which is also why phones sound thin.' },
      ],
    },
    {
      key: 'shorter-waves',
      lesson: 'what-is-sound',
      author: 'amira',
      daysAgo: 5.2,
      votes: 3,
      body: 'Why do the waves look closer together at 880 Hz? The screen is the same width for every tone.',
      replies: [
        {
          key: 'daniel',
          author: 'daniel',
          daysAgo: 5.0,
          accepted: true,
          votes: 4,
          body: 'The screen shows the same stretch of time for each tone. At 880 Hz, twice as many waves fit into that time as at 440 Hz, so each one is half as wide. Higher frequency, shorter wavelength.',
        },
      ],
    },
    {
      key: 'humming',
      lesson: 'beats',
      author: 'felix',
      daysAgo: 6.0,
      votes: 4,
      body: 'Try humming along with the 440 Hz tone: you can hear beats between your voice and the tone, and they slow down as you get closer to the note.',
      replies: [],
    },
  ],
  'neural-networks': [
    {
      key: 'nudges',
      lesson: 'backpropagation',
      author: 'priya',
      daysAgo: 3.5,
      votes: 3,
      body: 'Is the “nudge” for each weight just the partial derivative of the cost with respect to that weight?',
      replies: [
        {
          key: 'sofia',
          author: 'sofia',
          daysAgo: 3.3,
          accepted: true,
          votes: 3,
          body: 'Yes. Averaged over the training examples, the nudges make up the negative gradient, and each component is a partial derivative of the cost with respect to one weight or bias. The next video in the series works through the calculus, if you want it.',
        },
      ],
    },
  ],
  'how-computers-work': [
    {
      key: 'sticky-note',
      lesson: 'logic-gates',
      author: 'fatima',
      daysAgo: 5.0,
      votes: 3,
      body: 'The truth table in the notes is now on a sticky note on my monitor. Thank you!',
      replies: [],
    },
  ],
  'first-civilizations': [
    {
      key: 'receipts',
      lesson: 'mesopotamia',
      author: 'amira',
      daysAgo: 16.0,
      votes: 3,
      body: 'Cuneiform starting as grain receipts is my favourite fact so far.',
      replies: [{ key: 'lina', author: 'lina', daysAgo: 15.8, votes: 1, body: 'Same! Writing, invented by accountants.' }],
    },
    {
      key: 'deserts',
      lesson: 'ancient-egypt',
      author: 'emma',
      daysAgo: 4.0,
      votes: 2,
      body: 'Interesting that deserts on both sides protected Egypt for so long: geography as a defence system.',
      replies: [
        {
          key: 'omar',
          author: 'omar',
          daysAgo: 3.8,
          votes: 2,
          body: 'Exactly. Compare Mesopotamia, open on several sides, which was conquered again and again. Worth a sentence in your essay.',
        },
      ],
    },
  ],
};

// Reports ------------------------------------------------------------------------------------------
// Which post (a thread, or one of its replies), who reported it, why, and how it was settled, if it was.

export const REPORTS = [
  {
    course: 'linear-algebra-visually',
    thread: 'study-group',
    reply: 'adam',
    reporter: 'noah',
    reason: 'off_topic',
    note: 'This thread is for the study group, not for selling things.',
    daysAgo: 3.4,
  },
  {
    course: 'physics-of-sound',
    thread: 'beat-apps',
    reply: 'oliver',
    reporter: 'sienna',
    reason: 'abuse',
    note: 'Unkind to people asking questions.',
    daysAgo: 2.95,
  },
  {
    course: 'linear-algebra-visually',
    thread: 'welcome',
    reply: 'hugo',
    reporter: 'priya',
    reason: 'spam',
    note: 'Offering to do people’s assignments for money.',
    daysAgo: 19.3,
    resolved: { action: 'hidden', daysAgo: 19.1 },
  },
];

// Live classes -------------------------------------------------------------------------------------
// startsInMinutes: from now (negative: in the past); rounded to the hour when hours away, else to
// five minutes. status: scheduled, live (started on time), ended (after endedAfterMinutes) or
// cancelled. createdDaysAgo: when it was scheduled. attendees: how many came (the transcript's
// authors and `include` among them). transcript: [minutes from the start, author, text, { hidden }].

export const LIVE = [
  {
    key: 'span-qa',
    course: 'linear-algebra-visually',
    host: 'daniel',
    title: 'Live Q&A: span, basis and independence',
    description: `A live question-and-answer hour on the span lesson: linear combinations, span, bases and linear independence. Bring the "Check yourself" questions and anything that felt shaky.

In this demo, the replay is the course's span lecture, standing in for the recording of the stream.`,
    provider: 'youtube',
    streamRef: 'k7RM-ot2NWY',
    recordingRef: 'k7RM-ot2NWY',
    startsInMinutes: -6 * 1440,
    durationMinutes: 60,
    status: 'ended',
    endedAfterMinutes: 58,
    createdDaysAgo: 10,
    attendees: { count: 17, include: ['amira'] },
    transcript: [
      [-6, 'priya', 'Hi all, early as usual'],
      [-4, 'kwame', 'Hello from Accra!'],
      [-3, 'hana', 'Evening everyone'],
      [-1, 'amira', 'Hi! My first live class here'],
      [1, 'daniel', 'Welcome, everyone! Today: span, basis and linear independence. Questions in the chat as we go, please.'],
      [4, 'lucas', 'Is the span of a single vector always a line?'],
      [5, 'daniel', 'Lucas: a line through the origin, unless the vector is zero. Then its span is just the origin itself.'],
      [9, 'grace', 'So two vectors that aren’t parallel always span the whole plane?'],
      [10, 'daniel', 'In 2D, yes, Grace. In 3D, two independent vectors span a plane, and you need a third one, off that plane, to reach all of space.'],
      [14, 'sara', 'Could you redo the (1, 2) and (2, 4) example?'],
      [16, 'amira', 'Ah, so (2, 4) adds nothing new because it’s on the same line. That’s what dependent means.'],
      [17, 'daniel', 'Exactly, Amira. One vector is a combination of the others, so it doesn’t grow the span.'],
      [21, 'mateo', 'Is a basis always î and ĵ?'],
      [22, 'daniel', 'Good question, Mateo: no. Any two independent vectors form a basis of the plane. î and ĵ are just the standard one.'],
      [26, 'noah', 'So the coordinates of a vector depend on which basis you choose. Mind blown.'],
      [29, 'zara', 'Will we use other bases later in the course?'],
      [30, 'daniel', 'Briefly, Zara, when we talk about change of basis. It’s at the heart of computer graphics.'],
      [34, 'oliver', 'Selling my notes for every course here, message me for prices', { hidden: true }],
      [37, 'priya', 'Can three vectors in 2D ever be independent?'],
      [38, 'daniel', 'No, Priya: in the plane, a third vector is always a combination of the other two. At most two independent vectors fit in 2D.'],
      [43, 'kwame', 'Great rule of thumb: at most n independent vectors in n dimensions.'],
      [47, 'hana', 'Thank you, this cleared up the check-yourself question for me'],
      [52, 'sienna', 'Will the replay be on this page?'],
      [53, 'daniel', 'Yes, Sienna, right here. Thanks for coming, everyone; see you at the next one!'],
      [55, 'lucas', 'Thanks Daniel!'],
      [56, 'amira', 'Thank you, very helpful'],
      [57, 'grace', 'Thanks!'],
    ],
  },
  {
    key: 'office-hours',
    course: 'linear-algebra-visually',
    host: 'daniel',
    title: 'Office hours: transformations and the determinant',
    description: `Bring your questions on linear transformations, matrix multiplication and the determinant, and we'll work through examples together.

A demo stand-in: the video here is the course's lecture on linear transformations, playing where the YouTube Live stream would be. The people in the room, the chat and the raised hands are the demo's scripted classmates.`,
    provider: 'youtube',
    streamRef: 'kYB8IZa5AuE',
    recordingRef: null,
    startsInMinutes: -10,
    durationMinutes: 60,
    status: 'live',
    createdDaysAgo: 4,
    attendees: { count: 11 },
    transcript: [
      [-9, 'priya', 'Hi all! Early again'],
      [-6, 'kwame', 'Evening everyone'],
      [-2, 'lucas', 'Is it about transformations today?'],
      [0, 'daniel', 'Hello everyone, we’re live! Today: transformations, composition and the determinant, driven by your questions.'],
      [1, 'hana', 'Hi Daniel!'],
      [3, 'sara', 'Could you start with why the origin has to stay fixed?'],
      [4, 'daniel', 'Sure, Sara: scale any vector by 0 and you get the zero vector. A linear map has to send that to zero too, so the origin can’t move.'],
      [6, 'mateo', 'Taking notes'],
      [8, 'grace', 'Can we do a shear example after this?'],
      [9, 'daniel', 'Yes, Grace: a shear is next on my list.'],
    ],
  },
  {
    key: 'sound-drop-in',
    course: 'physics-of-sound',
    host: 'daniel',
    title: 'Drop-in: beat lab questions',
    description: `Stuck on the beat lab, or curious about decibels and harmonics? Drop in for 45 minutes of questions.

The meeting opens in a new tab when it's time; the waiting room and chat here open 15 minutes before.`,
    provider: 'link',
    streamRef: 'https://meet.example.com/grand-academy/sound-drop-in',
    recordingRef: null,
    startsInMinutes: 20,
    durationMinutes: 45,
    status: 'scheduled',
    createdDaysAgo: 3,
  },
  {
    key: 'rivers-seminar',
    course: 'first-civilizations',
    host: 'omar',
    title: 'Essay workshop: why rivers?',
    description: `A workshop for the essay "Why rivers?". We'll look at what makes a strong argument, how to use the Indus Valley, Mesopotamia and Egypt as evidence, and how to handle what rivers made harder. Bring a draft, or just your notes.`,
    provider: 'link',
    streamRef: 'https://meet.example.com/grand-academy/rivers-seminar',
    recordingRef: null,
    startsInMinutes: 2 * 1440,
    durationMinutes: 60,
    status: 'scheduled',
    createdDaysAgo: 1,
  },
  {
    key: 'derivatives-drop-in',
    course: 'calculus-first-steps',
    host: 'daniel',
    title: 'Derivatives drop-in',
    description: `Questions on the paradox of the derivative and the motion lesson.

Cancelled: I'm away at a conference this week. Post your questions in the discussions and I'll answer them there.`,
    provider: 'youtube',
    streamRef: null,
    recordingRef: null,
    startsInMinutes: 1440 + 120,
    durationMinutes: 45,
    status: 'cancelled',
    createdDaysAgo: 5,
    cancelledDaysAgo: 1,
  },
];

// The scripted classmates' chat -----------------------------------------------------------------------
// Per course: lines (a remark, or { ask, answer }: a question, and what the host answers when the host
// isn't the visitor; {name} is the asker's first name) and hands (what someone who raised a hand
// types once called on: nobody speaks in the demo, which has no LiveKit). The rest is said in any class.

export const LIVE_CHAT = {
  arrivals: ['Hi everyone!', 'Hello {host}!', 'Evening all', 'Hi! Just made it', 'Hello from the bus, audio only today', 'Hi all, glad to be here', 'Morning from my side of the world!', 'Hey everyone'],
  waiting: [
    'Early as usual',
    'Is it starting on time?',
    'Hi all, waiting room crew',
    'Coffee ready, notebook ready',
    'Anyone else here early?',
    'Looking forward to this one',
    'Hope we get to the questions from the discussions',
    'Can everyone see my messages?',
  ],
  openings: ['Hello everyone, we’re live! Give me a moment to share my screen.', 'Welcome, everyone! Questions in the chat as we go, please.', 'Hi all, thanks for coming. Let’s get started.'],
  reactions: ['Thanks!', 'That makes sense now.', 'Got it, thank you.', 'Ah, that helps a lot.', 'Writing that down.'],
  hostReplies: [
    'Good question, {name}. Let me show that on screen in a moment.',
    'Thanks {name}, I’ll pick that up right after this example.',
    '{name}, great question. Hold on to it: it’s exactly where we’re heading next.',
    'Let me come back to that, {name}. Remind me if I forget!',
  ],
  echoes: ['Good question, {name}', '+1, I was wondering the same', 'Same question here'],
  replies: ['Agreed, {name}!', 'Same here', 'Ha, exactly'],
  // A raised hand, called on: the host's call ({name}: the student), and how the student starts typing their question.
  handCalls: ['Go ahead, {name}: type your question and I’ll take it next.', 'I see your hand, {name}. Pop your question in the chat.', '{name}, your hand’s up: what’s your question?'],
  floor: ['Thanks! Here it is: ', 'Thank you! My question: ', 'Thanks, quick one: '],
  // The host, as the class ends on time.
  closings: ['That’s all for today, thanks everyone! The chat stays on this page.', 'Thanks for coming, everyone. See you next time!', 'We’re out of time. Thank you all, and good luck with the next lesson!'],

  courses: {
    'linear-algebra-visually': {
      lines: [
        { ask: 'Can you go over why the determinant of a shear is 1 again?', answer: '{name}, sure: a shear slides the top of the square sideways but keeps its base and its height, so the area stays the same. For columns (1, 0) and (1, 1), ad − bc = 1·1 − 1·0 = 1.' },
        { ask: 'So the columns are literally where î and ĵ land? That’s it?', answer: 'That’s it, {name}. Column one is where î lands, column two is where ĵ lands, and every other vector comes along for the ride.' },
        'The animation of the grid staying evenly spaced is so satisfying',
        { ask: 'Is matrix multiplication ever commutative?', answer: 'Sometimes, {name}: two rotations commute, and every matrix commutes with the identity. But in general AB and BA differ, so never assume it.' },
        { ask: 'What happens to the determinant if you swap the two columns?', answer: 'It changes sign, {name}. Swapping the columns flips the orientation, so the area stays the same but the determinant goes negative.' },
        'I keep reading BA as A then B... right to left, right to left',
        { ask: 'Does a determinant of 0 always mean the plane gets squished onto a line?', answer: 'Onto a line, or all the way down to a single point, {name}. Either way, areas become zero and the transformation can’t be undone.' },
        'Love that the 2×2 formula finally makes sense as an area',
        { ask: 'Is a reflection a linear transformation?', answer: 'Yes, {name}: reflecting across a line through the origin keeps grid lines parallel and evenly spaced. Its determinant is −1.' },
        'Taking notes like mad',
        { ask: 'Could you show a 3D example of the determinant at some point?', answer: 'Good idea, {name}. In 3D it’s the factor by which volumes change: the unit cube becomes a slanted box, and the determinant is that box’s volume.' },
        'Rewinding the lecture in another tab to compare',
        { ask: 'So if two columns are parallel, the determinant is 0?', answer: 'Exactly, {name}: parallel columns mean the square collapses onto a line, which has no area.' },
        'This is way clearer than my university lecture was',
        { ask: 'Quick check: a 90° rotation has columns (0, 1) and (−1, 0)?', answer: 'Yes, {name}, that’s the counter-clockwise one.' },
        { ask: 'What’s the difference between a linear and an affine transformation?', answer: '{name}, an affine transformation is a linear one followed by a shift. Shifts move the origin, so they aren’t linear on their own.' },
        'Pausing to sketch this, back in a minute',
        { ask: 'Does the project need a drawing, or is a description enough?', answer: 'A drawing, please, {name}. A photo of a sketch on paper is perfect.' },
        'The “recipe stays the same, ingredients move” idea from the discussions helped me a lot',
        { ask: 'Can a transformation have a negative determinant without a reflection in it?', answer: 'No, {name}: a negative determinant always means orientation has flipped, which is what a reflection does, possibly combined with a rotation or a stretch.' },
        'Matrix times vector = that much of column one plus that much of column two. Writing that on my wall.',
        { ask: 'Is the inverse of a rotation just rotating back?', answer: 'Yes, {name}: rotating by −θ undoes rotating by θ. Its matrix is also the transpose, a nice surprise for later.' },
        'Great pace today',
        { ask: 'How do we know grid lines stay parallel after composing two transformations?', answer: '{name}, each one keeps them parallel and evenly spaced, so doing one after the other does too. That’s why the composition is linear and has a matrix of its own.' },
        'Thank you, the shear example made it click',
        { ask: 'Is there a picture for the trace too?', answer: 'There is, {name}, though it’s subtler: it’s the sum of the eigenvalues. Eigenvalues come in a later course.' },
      ],
      hands: [
        'how would you explain the determinant to someone who has never seen a matrix?',
        'if I compose a rotation with a shear, what happens to the determinant?',
        'is there a quick way to tell whether two vectors are independent, without drawing them?',
        'for the project, can I use a matrix with a negative determinant?',
        'why does the order of multiplication matter when the order of addition doesn’t?',
      ],
    },
    'calculus-first-steps': {
      lines: [
        { ask: 'Why does the derivative of t³ have a 3 in front?', answer: '{name}, expand (t + dt)³: the change is 3t²·dt plus terms with dt² and dt³, which vanish as dt shrinks. Three slabs on the cube, each t² in area.' },
        'The rings-to-triangle trick for the circle is beautiful',
        { ask: 'Is velocity the slope of the position graph?', answer: 'Yes, {name}: velocity is the derivative of position, so it’s the slope of the position–time graph at each moment.' },
        'dt shrinking towards zero but never being zero still breaks my brain a bit',
        { ask: 'For the falling phone, do we ignore air resistance?', answer: 'Yes, {name}, ignore it, and say so in your answer. Use 9.8 m/s² for g.' },
        'Writing down: velocity is the derivative of position, acceleration of velocity',
        { ask: 'Why is the area under the velocity graph the distance travelled?', answer: '{name}, each thin slice is velocity times a tiny time, which is a tiny distance. Add up the slices and you get the whole distance. That’s the integral.' },
        'Hello all, joining a bit late',
        { ask: 'What does a negative derivative mean?', answer: 'The quantity is decreasing there, {name}. For position, it means moving backwards.' },
        'This makes so much more sense with pictures',
        { ask: 'Is acceleration always constant in free fall?', answer: 'Near the Earth’s surface and without air resistance, yes, {name}: about 9.8 m/s² downward.' },
        'Pausing to try x = t² myself',
        { ask: 'What’s the derivative of a constant?', answer: 'Zero, {name}: a constant doesn’t change, so its slope is flat everywhere.' },
        'The tangent line animation helped a lot',
        { ask: 'Are derivatives and integrals really opposites?', answer: 'In a precise sense, yes, {name}: that’s the fundamental theorem of calculus. Integrate a rate of change and you get the total change.' },
        'Finally passed the quick check',
        'Good evening everyone',
        { ask: 'Why call it “instantaneous” if we need two points?', answer: '{name}, the derivative isn’t measured at one point: it’s the value the ratio approaches as the two points get closer. That limit is what “instantaneous” means.' },
        'Can we do one more falling example?',
        'x = x₀ + v₀t + ½at² is going on a sticky note',
        'Love these sessions',
      ],
      hands: [
        'how do I know when to use the constant-acceleration equations and when not to?',
        'can you show why the derivative of t² is 2t with the same slab picture?',
        'what’s the best way to check my answer for the falling phone?',
        'is there an intuitive way to see why the area of a circle is πR²?',
      ],
    },
    'physics-of-sound': {
      lines: [
        { ask: 'So 220, 440 and 880 Hz are all the note A?', answer: 'Yes, {name}: doubling the frequency raises the note by an octave, and notes an octave apart share a name.' },
        'Headphones on, this sounds great',
        { ask: 'Why do 444 and 440 Hz give 4 beats a second, not 8?', answer: '{name}, the beat rate is the difference of the frequencies: 444 − 440 = 4 times a second the two waves come back into step.' },
        'Just tried humming against the 440 tone, I can hear the beats!',
        { ask: 'Is 10 dB really ten times the energy?', answer: 'Yes, {name}. +10 dB is ×10 energy, +20 dB is ×100, and our ears hear each +10 dB as roughly twice as loud.' },
        'My cat does not appreciate the 880 Hz tone',
        { ask: 'What makes a violin and a flute sound different on the same note?', answer: 'Their harmonics, {name}: the same fundamental, so the same pitch, but a different mix of harmonics, so a different timbre.' },
        'The waveform drawing itself as it plays is so cool',
        { ask: 'Why do older people stop hearing high frequencies?', answer: '{name}, the hair cells in the inner ear that respond to high frequencies wear out first, so the top of our range drops with age.' },
        'Hi all, made it just in time',
        { ask: 'Does a louder sound travel faster?', answer: 'No, {name}: in air, all sounds travel at about 343 m/s, loud or quiet, high or low.' },
        'Taking notes on harmonics for the lab',
        { ask: 'For the beat lab, how long should we count for?', answer: 'Ten seconds is a good start, {name}. Divide by ten for beats per second, and count twice.' },
        'Who else is doing the lab with two phones?',
        { ask: 'Why does a clarinet sound hollow?', answer: 'Mostly odd harmonics, {name}: it behaves like a tube closed at one end, which only supports odd multiples of the fundamental.' },
        'This is my favourite course so far',
        { ask: 'Is pitch exactly the same thing as frequency?', answer: 'Close, {name}: frequency is what we measure, pitch is what we hear. For pure tones they go together very closely.' },
        'The beats video is mesmerising',
        { ask: 'Counted 19 beats in ten seconds for 440 and 442 Hz. Close enough to 20?', answer: 'Very close, {name}: counting by ear always slips a beat or so. Count twice and take the average.' },
        'The equaliser on my mixing software makes so much more sense now',
        { ask: 'What’s the lowest note a person can hear?', answer: 'Around 20 Hz, {name}. Below that we feel vibrations more than we hear a pitch.' },
        'Thanks for these drop-ins, super helpful',
      ],
      hands: [
        'if two notes are an octave apart, do they beat at all?',
        'why do my beat counts drift when I try 440 and 446 Hz?',
        'how does noise cancelling work? Is it the same adding-waves idea?',
        'does the room I’m in change the timbre I hear?',
      ],
    },
    'first-civilizations': {
      lines: [
        { ask: 'Is it fair to say rivers caused civilization, or only made it possible?', answer: '{name}, “made it possible” is the safer claim. Rivers gave water, rich soil and transport, but people still had to organise irrigation and storage.' },
        'Hi everyone, essay draft open in another tab',
        { ask: 'Can we use the Indus Valley as evidence even though we can’t read its script?', answer: 'Yes, {name}. Archaeology tells us a lot: planned cities, drains, standard bricks and granaries all point to organisation around the rivers.' },
        'Salinisation is my secret weapon for the “what rivers made harder” part',
        { ask: 'How many words should the essay be again?', answer: '300 to 500, {name}. At least two civilizations as evidence, and one thing rivers made harder.' },
        'Cuneiform starting as grain receipts will never stop being funny to me',
        { ask: 'Were the Nile floods predictable?', answer: 'Remarkably, {name}: they came at about the same time every year, which let Egyptians plan around them. The Tigris and Euphrates were far less reliable.' },
        'Good evening all',
        { ask: 'Did all early civilizations grow along rivers?', answer: 'The earliest mostly did, {name}, but not every later one. It’s worth asking why river valleys came first.' },
        'Taking notes on Egypt vs Mesopotamia flooding',
        { ask: 'Is it OK to quote the lectures in the essay?', answer: 'Yes, {name}, briefly, and say which lecture. Your own argument should do most of the work.' },
        'I’m writing about disease from living close together as the downside',
        { ask: 'Why did Egypt stay stable for so long?', answer: '{name}, deserts on both sides kept invaders out, and the Nile’s regular floods kept harvests dependable. Geography helped a lot.' },
        'This workshop is exactly what I needed',
        { ask: 'What’s the difference between a village and a city here?', answer: 'Size, but also specialisation, {name}: in a city, many people don’t farm at all. That’s only possible with a surplus.' },
        'The agricultural revolution lecture really sets all this up',
        { ask: 'Was Hammurabi’s code the first written law?', answer: 'Not quite, {name}: older Sumerian codes exist, such as Ur-Nammu’s. Hammurabi’s is the most complete early one we have.' },
        'Hi from the library!',
        'Can’t wait to hear the feedback on my essay',
        { ask: 'Do I need a conclusion paragraph?', answer: 'Yes, {name}, a short one: answer the question directly, in a sentence or two.' },
      ],
      hands: [
        'how much should I write about the downside of rivers compared with the benefits?',
        'can I compare all three civilizations, or is two better for depth?',
        'is irrigation a cause or a consequence of the first cities?',
      ],
    },
    'how-computers-work': {
      lines: [
        { ask: 'Is XOR made from other gates?', answer: 'It can be, {name}: (A OR B) AND NOT (A AND B). At least one, but not both.' },
        'NAND being universal blows my mind',
        { ask: 'Why did relays wear out?', answer: '{name}, they’re mechanical: a little arm physically moves every time they switch, so the contacts wear down.' },
        'Hello everyone!',
        { ask: 'How many transistors does a gate take?', answer: 'Just a few, {name}: a NAND gate in a modern chip takes four.' },
        'Truth tables are oddly relaxing',
        { ask: 'Why binary and not decimal?', answer: '{name}, two states are easy to tell apart reliably with electricity: on or off, high or low voltage. Ten levels would be far more error-prone.' },
        'Leibniz’s Step Reckoner looks amazing',
        { ask: 'Was the abacus really a computer?', answer: 'A calculating tool, {name}: it helps a person compute, but the person does the computing. That difference matters for what comes next.' },
        'My truth table for the assignment finally works',
        { ask: 'What does (NOT A) AND B give when A is true?', answer: 'False, {name}: NOT A is false, and false AND anything is false.' },
        'The vacuum tubes in the old photos look like little light bulbs',
        { ask: 'Is a transistor just a switch?', answer: 'In digital circuits, essentially yes, {name}: a switch controlled by electricity, with no moving parts.' },
        'Joining from my lunch break',
        { ask: 'How did punch cards store data?', answer: '{name}, a hole or no hole in each position: a yes or a no, which is really a bit.' },
        'This is the clearest explanation of logic gates I’ve seen',
        { ask: 'Who invented the transistor?', answer: 'John Bardeen, Walter Brattain and William Shockley, at Bell Labs in 1947, {name}.' },
        'Writing out all eight rows by hand, wish me luck',
        'Thanks for doing these live sessions',
        { ask: 'Can every computation really be built from gates?', answer: 'Everything a digital computer does, {name}, yes: arithmetic, memory and control are all built from gates.' },
      ],
      hands: ['how would I build NOT out of NAND gates?', 'why did computers move from relays to tubes so quickly?', 'how does a computer add two numbers with gates?'],
    },
    'neural-networks': {
      lines: [
        { ask: 'Why do we need the sigmoid or ReLU at all?', answer: '{name}, without a nonlinear step, stacked layers collapse into a single linear map. The squashing is what lets depth add power.' },
        '13,000 weights for a tiny network is wild',
        { ask: 'Is the cost function always squared error?', answer: 'No, {name}: squared error is the one in the lectures, but networks that classify things usually use cross-entropy.' },
        'The rolling-downhill picture of gradient descent really helps',
        { ask: 'What’s a mini-batch, exactly?', answer: 'A small random handful of training examples, {name}. Each step uses one: much cheaper, and still roughly downhill.' },
        'Hi all!',
        { ask: 'Do the middle layers really learn edges and loops?', answer: 'Sometimes something like it, {name}, but often not cleanly. The lecture’s “hope” is tidier than reality.' },
        'Backprop going backwards finally makes sense',
        { ask: 'How big should the learning rate be?', answer: '{name}, big enough to make progress, small enough not to overshoot. In practice people try a few values and watch the cost.' },
        'Pausing to rewatch the gradient part',
        { ask: 'Can gradient descent get stuck?', answer: 'It can settle in a local minimum, {name}, but for large networks most of those turn out to be nearly as good as each other.' },
        'This connects so well with linear algebra',
        { ask: 'Is a neuron here anything like a real neuron?', answer: 'Loosely inspired, {name}, but here it’s just a number between 0 and 1. Real neurons are far more complicated.' },
        'Watching from my phone, the animations still work great',
        { ask: 'What’s the bias for?', answer: '{name}, it shifts when a neuron becomes active: how high the weighted sum must be before it lights up.' },
        'The 784 input neurons = 28×28 pixels thing finally clicked',
        { ask: 'How many training examples does the digit network see?', answer: 'The classic MNIST set has 60,000 training images, {name}.' },
        'Love these Q&As',
        { ask: 'Why go backwards and not forwards when working out the nudges?', answer: '{name}, each layer’s nudge depends on how the next layer should change, so you start at the output and work back. It saves a huge amount of repeated work.' },
        'Thanks for explaining it without the equations first',
      ],
      hands: [
        'how could I explain gradient descent to a friend without the hill analogy?',
        'is there a rule of thumb for how many layers to use?',
        'does backpropagation need the whole training set at once?',
      ],
    },
    'code-your-first-website': {
      lines: [
        { ask: 'Do I need to close every tag?', answer: 'Most of them, {name}. A few, like <img> and <br>, have no closing tag at all.' },
        'My first page is live on my desktop!',
        { ask: 'What’s the alt attribute for?', answer: '{name}, it describes the image for people who can’t see it, and shows if the image fails to load.' },
        'VS Code’s autocomplete is magic',
        { ask: 'Why is my image not showing?', answer: 'Check the path in src, {name}: it’s relative to your index.html, and capitals and extensions must match exactly.' },
        'Hello from Lisbon!',
        { ask: 'What goes in the head and what goes in the body?', answer: '{name}, information about the page (its title, its character set) goes in the head; everything people see goes in the body.' },
        'Lists inside lists, my page is getting fancy',
        { ask: 'Can I have more than one h1?', answer: 'You can, {name}, but use one main h1 per page and h2s for its sections. It keeps the outline clear, for screen readers too.' },
        'Pausing the lecture to catch up',
        { ask: 'What’s the difference between a link and a button?', answer: '{name}, a link takes you somewhere; a button does something on the page. Use each for its job.' },
        'Typing every example myself really helps',
        { ask: 'Should I use tables for layout?', answer: 'No, {name}: tables are for tables of data. Layout is CSS’s job, which comes next.' },
        'My page is about my grandmother’s recipes',
        { ask: 'How do I make a link open in a new tab?', answer: 'Add target="_blank" to the a tag, {name}, together with rel="noopener noreferrer", so the new page can’t reach back into yours.' },
        'This is so much fun',
        { ask: 'Do file names matter?', answer: 'Yes, {name}: keep them lowercase with no spaces, like my-photo.jpg. It saves a lot of broken links.' },
        'Can’t believe how much I’ve built in one week',
        { ask: 'What’s the doctype line for?', answer: '{name}, it tells the browser to use modern standards mode. Always put <!doctype html> first.' },
        'Thanks for this session!',
      ],
      hands: ['how do I put my page online so friends can see it?', 'what should I learn after HTML?', 'how do I make an image smaller on the page?'],
    },
    'big-ideas': {
      lines: [
        { ask: 'Why do protons stick together if they repel each other?', answer: 'The strong nuclear force, {name}: at very short distances it’s far stronger than the electric repulsion.' },
        'Astronomy is my favourite of the four',
        { ask: 'What’s an opportunity cost, in one sentence?', answer: '{name}, the next-best thing you gave up to make a choice.' },
        'Hi everyone!',
        { ask: 'Is psychology really a science?', answer: 'Yes, {name}: it tests ideas about behaviour and the mind with experiments and data, like any science.' },
        'The nucleus lecture was my surprise favourite',
        { ask: 'How do astronomers know what stars are made of?', answer: 'From their light, {name}: each element leaves its own pattern of lines in a star’s spectrum.' },
        'Writing my “which subject next” answer now',
        { ask: 'What’s the difference between micro and macro economics?', answer: '{name}, micro looks at individual people and firms; macro at whole economies: growth, inflation, unemployment.' },
        'I want to study all four now',
        { ask: 'What’s an isotope?', answer: 'Atoms of the same element with different numbers of neutrons, {name}: the same protons, a different mass.' },
        'Joining from a café, the stream is smooth',
        { ask: 'Can anyone start observing the night sky?', answer: 'Absolutely, {name}: your eyes are enough to start. Binoculars are a great next step.' },
        'Economics in ten minutes was impressive',
        { ask: 'Where did psychology come from?', answer: '{name}, it grew out of philosophy and biology, and became a science of its own in the late 1800s.' },
        'Love the variety in this course',
        { ask: 'Is scarcity really everywhere?', answer: 'In the economist’s sense, yes, {name}: time and resources are limited, so every choice gives something up.' },
        'My answer for the assignment: astronomy, obviously',
        'Thank you, this was fun',
        { ask: 'Which subject do most students pick for the assignment?', answer: 'It’s spread out, {name}, but astronomy is a little ahead so far.' },
      ],
      hands: ['which of the four subjects would you recommend for a complete beginner?', 'how do the four subjects connect, if at all?', 'is there a follow-up course for astronomy?'],
    },
  },

  /** For a course without its own pool. */
  fallback: {
    lines: [
      { ask: 'Could you go over that last example again?', answer: 'Of course, {name}: let me walk through it once more, step by step.' },
      'Hi everyone!',
      'Taking notes',
      { ask: 'Will the slides be shared after the class?', answer: 'Yes, {name}, I’ll post them in the course discussions afterwards.' },
      'This is really helpful',
      { ask: 'Is this going to be on the quiz?', answer: 'The ideas will be, {name}, though not this exact example.' },
      'Great explanation',
      'Pausing to catch up on my notes',
      { ask: 'Where can I read more about this?', answer: 'The lesson notes have the key ideas, {name}, and I’ll add a reading list to the discussions.' },
      'Hello from the train, audio only today',
      { ask: 'Can you say that last part a bit slower?', answer: 'Sure, {name}. I’ll go through it again more slowly.' },
      'Love these live sessions',
      { ask: 'How long is the class today?', answer: 'About an hour, {name}, with time for questions at the end.' },
      'The examples really help',
      { ask: 'Is it OK to ask about the assignment here?', answer: 'Absolutely, {name}: ask away.' },
      'Following along, thanks!',
      'Good evening everyone',
      { ask: 'Could you recommend a good way to practise this?', answer: 'Try the exercises in the lesson notes first, {name}, then explain one to a friend.' },
      'Thanks for this session!',
      'Writing this down',
    ],
    hands: ['could you give one more example of that?', 'how does this connect to the previous lesson?', 'what’s the most common mistake people make with this?'],
  },
};
